// Generated by CoffeeScript 1.8.0
(function() {
  var config, userDao;

  config = require("cloud/config/config");

  userDao = require(config.ROOT + "dao/userDao");

  AV.Cloud.beforeSave('Favorite', function(request, response) {
    var favo, post;
    favo = request.object;
    post = favo.get('post');
    post.increment('favoriteCount', 1);
    return userDao.save(post, function(error, result) {
      return post.fetch({
        success: function(post) {
          favo.set('publishType', post.get('publishType'));
          favo.save();
          return response.success();
        },
        error: function(post, error) {}
      });
    });
  });

  AV.Cloud.beforeDelete('Favorite', function(request, response) {
    var favo, post;
    favo = request.object;
    post = favo.get('post');
    post.increment('favoriteCount', -1);
    return userDao.save(post, function(error, result) {
      return response.success();
    });
  });

  AV.Cloud.beforeSave('Like', function(request, response) {
    var favo, post;
    favo = request.object;
    post = favo.get('post');
    post.increment('likeCount', 1);
    return userDao.save(post, function(error, result) {
      return response.success();
    });
  });

  AV.Cloud.beforeDelete('Like', function(request, response) {
    var favo, post;
    favo = request.object;
    post = favo.get('post');
    post.increment('likeCount', -1);
    return userDao.save(post, function(error, result) {
      return response.success();
    });
  });

  AV.Cloud.beforeSave('Comment', function(request, response) {
    var favo, post;
    favo = request.object;
    post = favo.get('post');
    post.increment('commentCount', 1);
    return userDao.save(post, function(error, result) {
      return response.success();
    });
  });

  AV.Cloud.beforeDelete('Comment', function(request, response) {
    var favo, post;
    favo = request.object;
    post = favo.get('post');
    post.increment('commentCount', -1);
    return userDao.save(post, function(error, result) {
      return response.success();
    });
  });

}).call(this);
