// Generated by CoffeeScript 1.7.1
(function() {
  var config, userService;

  config = require("../config/config");

  userService = require(ROOT + 'service/userService');

  AV.Cloud.define("hello", function(request, response) {
    response.success("Hello world!");
  });

  AV.Cloud.define("register", function(request, response) {
    return response.success("success");
  });

}).call(this);
