// Generated by CoffeeScript 1.8.0
(function() {
  var daoHelper;

  daoHelper = require("./daoHelper");

  exports.insert = function(businessPromotion, callback) {
    daoHelper.sql("insert into businessPromotion set ?", businessPromotion, callback);
  };

}).call(this);
