// Generated by CoffeeScript 1.8.0
(function() {
  var daoHelper;

  daoHelper = require("./daoHelper");

  exports.insert = function(businessImage, callback) {
    daoHelper.sql("insert into businessImage set ?", businessImage, callback);
  };

}).call(this);
