// Generated by CoffeeScript 1.8.0
(function() {
  var daoHelper;

  daoHelper = require("./daoHelper");

  exports.insert = function(businessReview, callback) {
    daoHelper.sql("insert into businessReview set ?", businessReview, callback);
  };

}).call(this);
