// Generated by CoffeeScript 1.8.0
(function() {
  var config, log4js, logger, mysql, pool, sql;

  sql = function(_sql, _args, callback) {
    var connection;
    connection = pool.getConnection(function(err, connection) {
      var query;
      if (err) {
        logger.error(err);
      }
      if (err) {
        sql(_sql, _args, callback);
        return;
      }
      query = connection.query(_sql, _args, function(err, result) {
        logger.debug("sql executed");
        connection.release();
        if (err) {
          logger.error(err);
        }
        if (callback) {
          callback(result, err);
        } else {

        }
      });
    });
  };

  config = require("../config/config");

  mysql = require("mysql");

  log4js = require("log4js");

  logger = log4js.getLogger(__filename);

  pool = mysql.createPool({
    host: config.dbHost,
    user: config.dbUser,
    database: config.dbDatabase,
    password: config.dbPassword
  });

  logger.debug("db initialized");

  exports.sql = sql;

}).call(this);
