// Generated by CoffeeScript 1.8.0
(function() {
  var config, log4js, logger, pool, poolModule, redis, release;

  release = function(client) {
    pool.release(client);
  };

  config = require("../config/config");

  log4js = require("log4js");

  logger = log4js.getLogger(__filename);

  poolModule = require("generic-pool");

  redis = require("redis");

  pool = poolModule.Pool({
    name: "redis",
    create: function(callback) {
      var client;
      if (config.local) {
        callback({
          errMsg: 'local debug'
        }, null);
        return;
      }
      client = redis.createClient(config.redisPort, config.redisHost);
      callback(null, client);
    },
    destroy: function(client) {
      client.quit();
    },
    max: 10,
    idleTimeoutMillis: 30000,
    log: true
  });

  module.exports = function(callback) {
    pool.acquire(function(err, client) {
      if (err) {
        logger.error("[" + __function + ":" + __line + "] " + err);
        callback(err, null);
        return;
      }
      client.end = function() {
        release(client);
      };
      callback(err, client);
    });
  };

}).call(this);
