// Generated by CoffeeScript 1.8.0
(function() {
  var config;

  config = {
    impl: 'AVOS',
    dbHost: "mysql.cfp3qdjt6nej.ap-northeast-1.rds.amazonaws.com",
    dbUser: "awsuser",
    dbPassword: "261103692",
    dbDatabase: "webapp",
    redisHost: "awsc.droyyu.0001.apne1.cache.amazonaws.com",
    redisPort: "6379",
    solr: {
      host: 'solr-fanhua.rhcloud.com',
      port: '',
      core: 'coolweb_collection',
      path: '/'
    }
  };

  config.ROOT = "cloud/";

  module.exports = config;

}).call(this);
