// Generated by CoffeeScript 1.8.0
(function() {
  var async, classMap, randomToken, userDao;

  randomToken = function() {
    return crypto.randomBytes(20).toString("hex");
  };

  userDao = require(ROOT + "dao/userDao");

  async = require("async");

  classMap = {};

  exports.addToLike = function(user, post, callback) {
    var publish;
    publish = AV.Object["new"]('Comment');
    publish.set('objectId', post);
    return userDao.queryByParam('Like', {
      author: user,
      post: publish
    }, function(error, results) {
      if (error) {
        return callback(error, null);
      } else {
        if (results.length > 0) {
          return callback(null, '已经赞过');
        } else {
          return userDao.insert('Like', {
            author: user,
            post: publish
          }, function(error, result) {
            if (!error) {
              return callback(null, '成功赞');
            }
          });
        }
      }
    });
  };

}).call(this);
