// Generated by CoffeeScript 1.8.0
(function() {
  var config;

  config = require("cloud/config/config");

  exports.searchNickname = function(param, callback) {
    return AV.Cloud.httpRequest({
      url: 'https://api.weibo.com/2/users/show.json',
      params: {
        access_token: param.accessToken,
        screen_name: param.who
      },
      success: function(httpResponse) {
        var responseObject, responseText;
        responseText = httpResponse.text;
        responseObject = JSON.parse(responseText);
        return callback(null, responseObject);
      },
      error: function(httpResponse) {
        var responseObject, responseText;
        responseText = httpResponse.text;
        responseObject = JSON.parse(responseText);
        return callback(responseObject);
      }
    });
  };

  exports.searchUID = function(param, callback) {
    return AV.Cloud.httpRequest({
      url: 'https://api.weibo.com/2/users/show.json',
      params: {
        access_token: param.accessToken,
        uid: param.who
      },
      success: function(httpResponse) {
        var responseObject, responseText;
        responseText = httpResponse.text;
        responseObject = JSON.parse(responseText);
        return callback(null, responseObject);
      },
      error: function(httpResponse) {
        var responseObject, responseText;
        responseText = httpResponse.text;
        responseObject = JSON.parse(responseText);
        return callback(responseObject);
      }
    });
  };

  exports.searchWeibo = function(param, callback) {
    return exports.searchNickname({
      accessToken: param.accessToken,
      who: param.who
    }, function(error, result) {
      if (!error) {
        return callback(null, result);
      } else {
        return exports.searchUID({
          accessToken: param.accessToken,
          who: param.who
        }, function(error, result) {
          if (!error) {
            return callback(null, result);
          } else {
            return callback(error, null);
          }
        });
      }
    });
  };

}).call(this);
