// Generated by CoffeeScript 1.8.0
(function() {
  var client, config, logger, options, solr;

  config = require(ROOT + "config/config");

  solr = require('solr-client');

  logger = require("log4js").getLogger(__filename);

  options = {
    url: 'https://solr-fanhua.rhcloud.com/coolweb_collection/select?q=*:*&fq=%7B!geofilt%7D&sort=geodist()+asc&rows=200&fl=*%2Cscore%2Cdistance%3Ageodist()&wt=json&indent=true&spatial=true&pt=32.0694%2C118.77998&sfield=location',
    timeout: 100000
  };

  client = solr.createClient(config.solr);

  exports.queryNearby = function(param, callback) {
    var date, query;
    logger.debug("[" + __function + ":" + __line + "] " + "start solr query ");
    date = new Date;
    query = client.createQuery().q('text:' + (param.q ? param.q : '*')).fq('{!geofilt}').sort('geodist() asc').rows(100).start(param.start ? param.start : 0).d(param.d ? param.d : 100).fl('*,score,distance:geodist()').spatial(true).pt(param.pt).sfield('location');
    return client.search(query, function(err, obj) {
      var endDate;
      if (err) {
        logger.error("[" + __function + ":" + __line + "] " + err);
        callback(err);
      }
      endDate = new Date;
      logger.info("[" + __function + ":" + __line + "] " + "end solr query cost " + (endDate.getTime() - date.getTime()));
      return callback(err, obj.response.docs);
    });
  };

}).call(this);
