// Generated by CoffeeScript 1.8.0
(function() {
  var readline;

  readline = require("readline");

  exports.rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

}).call(this);
