// Generated by CoffeeScript 1.8.0
(function() {
  var config, userDao;

  config = require("cloud/config/config");

  if (config.impl === 'AVOS') {
    userDao = require(config.ROOT + 'dao/userDaoAVImpl');
  } else {
    userDao = require(config.ROOT + 'dao/userDaoImpl');
  }

  module.exports = userDao;

}).call(this);
