// Generated by CoffeeScript 1.8.0
(function() {
  var multiline;

  multiline = require('multiline');

  exports.command_query = multiline(function() {

    /*
    what command ?
     */
  });

  exports.list_users = 'list_users';

  exports.add_job = 'add_job';

  exports.help = 'help';

  exports.ok = 'ok';

  exports.ask_url = 'please enter the url of product';

  exports.adding = multiline(function() {

    /*
    adding job to user:%s
     */
  });

  exports.welcome = multiline(function() {

    /*
     *welcome
     *
     *     cmd list:
     *         %s
     *         %s
     *         %s
     */
  });

}).call(this);
